### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by rtsisyk** [viciious/tarantool-graphite#8]
https://github.com/tarantool/graphite/blob/master/graphite.lua#L231

```
                local sf = fiber.create(function()
                        sock = socket('AF_INET', 'SOCK_DGRAM', 'udp')

                        if sock ~= nil then
```

Please don't wait for the garbage collector and `:close()` socket after finishing use it.

**Comment by viciious** [comment]
Resolved by @zlobspb in 28575316654e8f2daf39e795fd58e7d33695fc51 (see graphite.stop)
